### ISSUE TITLE
Create image for specific flutter version and channel with flutter web enable

### ISSUE THREAD

**Issue by parimalyeole1** [cirruslabs/docker-images-flutter#80] opened 2020-07-31 09:23 UTC
How can I use this repo to create image locally for following version with flutter we enable

`Flutter 1.19.0-4.3.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 8fe7655ed2 (4 weeks ago) • 2020-07-01 14:31:18 -0700
Engine • revision 9a28c3bcf4
Tools • Dart 2.9.0 (build 2.9.0-14.1.beta)`

by using image I need to do |
> flutter analyze
> flutter build web
> flutter test -d web-server --platform chrome

**Comment by fkorotkov** [comment] 2020-09-11 12:07
Duplicate of #66

**Closed by fkorotkov** 2020-09-11 12:07 UTC
